// Command permgen generates a service's permission constants from Identity's
// published OpenAPI. A consuming service depends on Identity's contract, never
// its code: this reads a YAML file and imports nothing under services/identity.
package main

import (
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

var errNoPermissionSchema = errors.New("no components.schemas.Permission.enum in the contract")

type contract struct {
	Components struct {
		Schemas struct {
			Permission struct {
				Enum []string `yaml:"enum"`
			} `yaml:"Permission"`
		} `yaml:"schemas"`
	} `yaml:"components"`
}

func main() {
	contractPath := flag.String("contract", "services/identity/openapi/identity.yaml", "OpenAPI file to read the vocabulary from")
	out := flag.String("out", "services/catalog/internal/permission/permission_gen.go", "file to write")
	pkg := flag.String("package", "permission", "package name for the generated file")
	flag.Parse()

	src, err := generate(*contractPath, *pkg)
	if err != nil {
		fmt.Fprintln(os.Stderr, "permgen:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "permgen:", err)
		os.Exit(1)
	}
}

func generate(contractPath, pkg string) ([]byte, error) {
	raw, err := os.ReadFile(contractPath)
	if err != nil {
		return nil, err
	}

	var doc contract
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		return nil, fmt.Errorf("parse %s: %w", contractPath, err)
	}

	names := doc.Components.Schemas.Permission.Enum
	// An empty vocabulary would make every permission check pass trivially, so
	// a contract that does not declare one is an error rather than an empty file.
	if len(names) == 0 {
		return nil, fmt.Errorf("%s: %w", contractPath, errNoPermissionSchema)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by tools/permgen. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: %s\n\npackage %s\n\n", contractPath, pkg)
	b.WriteString("type Permission string\n\nconst (\n")
	for _, name := range names {
		fmt.Fprintf(&b, "\t%s Permission = %q\n", exported(name), name)
	}
	b.WriteString(")\n\nfunc All() []string {\n\treturn []string{\n")
	for _, name := range names {
		fmt.Fprintf(&b, "\t\tstring(%s),\n", exported(name))
	}
	b.WriteString("\t}\n}\n")

	return format.Source([]byte(b.String()))
}

func exported(permission string) string {
	var b strings.Builder
	for _, part := range strings.Split(permission, "_") {
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(part[1:])
	}
	return b.String()
}
