package main

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeContract(t *testing.T, body string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "contract.yaml")
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatalf("write contract: %v", err)
	}
	return path
}

func TestGenerateProducesConstantsAndAll(t *testing.T) {
	path := writeContract(t, `
components:
  schemas:
    Permission:
      type: string
      enum:
        - view_staff
        - edit_products
`)

	src, err := generate(path, "permission")
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	// gofmt aligns the const block, so compare with runs of spaces collapsed.
	got := strings.Join(strings.Fields(string(src)), " ")

	for _, want := range []string{
		"// Code generated by tools/permgen. DO NOT EDIT.",
		`ViewStaff Permission = "view_staff"`,
		`EditProducts Permission = "edit_products"`,
		"func All() []string",
	} {
		if !strings.Contains(got, strings.Join(strings.Fields(want), " ")) {
			t.Errorf("generated source missing %q:\n%s", want, src)
		}
	}
}

// An empty vocabulary would make every permission check pass trivially, so a
// contract declaring none must fail rather than write an empty file.
func TestGenerateRefusesAContractWithNoVocabulary(t *testing.T) {
	path := writeContract(t, "components:\n  schemas:\n    Error:\n      type: object\n")

	if _, err := generate(path, "permission"); !errors.Is(err, errNoPermissionSchema) {
		t.Fatalf("want errNoPermissionSchema, got %v", err)
	}
}

func TestGenerateRefusesAMissingContract(t *testing.T) {
	if _, err := generate(filepath.Join(t.TempDir(), "absent.yaml"), "permission"); err == nil {
		t.Fatal("a missing contract was accepted")
	}
}

func TestGeneratedSourceIsFormatted(t *testing.T) {
	path := writeContract(t, "components:\n  schemas:\n    Permission:\n      enum: [view_orders]\n")

	src, err := generate(path, "permission")
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	// generate runs format.Source, so a syntax error surfaces here rather than
	// as an unbuildable package in whichever service consumes it.
	if !strings.HasSuffix(string(src), "}\n") {
		t.Errorf("source does not end cleanly:\n%s", src)
	}
}
