// Code generated by tools/permgen. DO NOT EDIT.
// Source: services/identity/openapi/identity.yaml

package permission

type Permission string

const (
	ViewStaff    Permission = "view_staff"
	EditStaff    Permission = "edit_staff"
	ViewRoles    Permission = "view_roles"
	EditRoles    Permission = "edit_roles"
	ViewProducts Permission = "view_products"
	EditProducts Permission = "edit_products"
	ViewOrders   Permission = "view_orders"
	EditOrders   Permission = "edit_orders"
)

func All() []string {
	return []string{
		string(ViewStaff),
		string(EditStaff),
		string(ViewRoles),
		string(EditRoles),
		string(ViewProducts),
		string(EditProducts),
		string(ViewOrders),
		string(EditOrders),
	}
}
